Train:
  batch_size: 1 # 5 for kitti and 100 for cifar works
  learning_rate: 0.001
  reg: 0
  epochs: 100
  steps: [6, 8]
  warmup: 0
  momentum: 0.9
  gamma: 1
  model_type: "attentionyolo" # tinyYOLO, simpleYOLO, EncoderDecoderYOLO, attentionYOLO
  data_type: "kitti" # cifar, kitti
  num_classes: 4

  # Between 0 and 1:
  training_split_percentage: 0.8
  dataset_percentage: 0.5
  save_delay_percent: 0
